"""Data layer for bundle authoring. No MCP, no FastMCP — just file I/O on dicts.

Every function in this module:
  - takes a bundle root Path and primitive data
  - writes (or reads) deterministic files inside that bundle
  - returns plain dicts with a 'written' list of relative paths

This separation lets us run the data layer in isolation (a CLI smoke test in
__main__) without dragging MCP into the loop.
"""
from __future__ import annotations

import json
import os
import shutil
import textwrap
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml  # PyYAML — already a dep via fastmcp

from .config import BUNDLE_LAYOUT, resolve_bundle_dir


# ---------------------------------------------------------------------------
# Init / skeleton
# ---------------------------------------------------------------------------

def init_bundle(slug: str, root_dir: str | None = None, overwrite: bool = False) -> dict[str, Any]:
    """Create the empty directory skeleton for a Codabench bundle.

    Returns the resolved bundle path and the directories that were created.
    Does NOT write competition.yaml — call write_competition_yaml for that.
    """
    bundle = resolve_bundle_dir(slug, root_dir)
    if bundle.exists():
        if not overwrite:
            return {
                "bundle_dir": str(bundle),
                "created": False,
                "reason": "exists; pass overwrite=True to replace",
            }
        shutil.rmtree(bundle)

    bundle.mkdir(parents=True, exist_ok=False)
    created_dirs: list[str] = []
    for d in BUNDLE_LAYOUT.values():
        (bundle / d).mkdir(parents=True, exist_ok=True)
        created_dirs.append(d)

    # A README so the agent and the human can both see what this folder is.
    readme = bundle / "README.md"
    readme.write_text(
        textwrap.dedent(
            f"""\
            # Bundle: {slug}

            Generated by autocodabench. To inspect, run the bundle's metadata.yaml
            check or invoke validate_bundle / zip_bundle from the MCP server.

            Layout:

            - `competition.yaml`           — written by write_competition_yaml
            - `pages/`                     — markdown pages referenced from competition.yaml
            - `scoring_program/`           — score.py + metadata.yaml
            - `ingestion_program/`         — (optional) ingestion.py + metadata.yaml
            - `reference_data/`            — ground truth used by scoring program
            - `input_data/`                — (optional) inputs given to a code submission
            - `solutions/`                 — example submission used as baseline + smoke test
            - `starting_kit/`              — files for participants to download
            - `public_data/`               — (optional) publicly downloadable data
            """
        ),
        encoding="utf-8",
    )
    return {
        "bundle_dir": str(bundle),
        "created": True,
        "directories": created_dirs,
        "readme": "README.md",
    }


# ---------------------------------------------------------------------------
# competition.yaml
# ---------------------------------------------------------------------------

# Allow-listed top-level keys we will accept from callers, matching
# Yaml-Structure.md. Unknown keys are rejected to catch typos early.
_COMPETITION_KEYS_REQUIRED = {"version", "title", "image", "terms", "pages", "phases", "tasks", "leaderboards"}
_COMPETITION_KEYS_OPTIONAL = {
    "description", "registration_auto_approve", "docker_image",
    "make_programs_available", "make_input_data_available",
    "enable_detailed_results", "show_detailed_results_in_submission_panel",
    "show_detailed_results_in_leaderboard", "contact_email", "reward",
    "auto_run_submissions", "can_participants_make_submissions_public",
    "forum_enabled", "queue", "solutions", "fact_sheet",
}
_COMPETITION_KEYS_ALL = _COMPETITION_KEYS_REQUIRED | _COMPETITION_KEYS_OPTIONAL


def write_competition_yaml(slug: str, payload: dict[str, Any], root_dir: str | None = None) -> dict[str, Any]:
    """Write competition.yaml at the bundle root.

    payload is the full YAML body as a dict. We validate keys against the
    Codabench spec and reject unknowns rather than silently writing them —
    the model should fail loudly on misnamed keys.
    """
    bundle = resolve_bundle_dir(slug, root_dir)
    if not bundle.exists():
        raise FileNotFoundError(f"bundle not initialised: {bundle}")

    if not isinstance(payload, dict):
        raise TypeError("payload must be a dict")

    payload.setdefault("version", 2)

    bad = set(payload.keys()) - _COMPETITION_KEYS_ALL
    if bad:
        raise ValueError(f"unknown competition.yaml keys: {sorted(bad)}")

    missing = _COMPETITION_KEYS_REQUIRED - set(payload.keys())
    if missing:
        raise ValueError(f"missing required competition.yaml keys: {sorted(missing)}")

    out_path = bundle / "competition.yaml"
    out_path.write_text(yaml.safe_dump(payload, sort_keys=False, allow_unicode=True), encoding="utf-8")
    return {"bundle_dir": str(bundle), "written": ["competition.yaml"]}


# ---------------------------------------------------------------------------
# pages
# ---------------------------------------------------------------------------

_ALLOWED_PAGE_EXTENSIONS = {".md", ".html"}


def write_page(slug: str, filename: str, body: str, root_dir: str | None = None) -> dict[str, Any]:
    """Write a single page markdown/html file under pages/."""
    bundle = resolve_bundle_dir(slug, root_dir)
    if not bundle.exists():
        raise FileNotFoundError(f"bundle not initialised: {bundle}")

    rel = Path(filename)
    if rel.is_absolute() or ".." in rel.parts:
        raise ValueError(f"page filename must be relative inside the bundle: {filename!r}")
    if rel.suffix.lower() not in _ALLOWED_PAGE_EXTENSIONS:
        raise ValueError(f"page filename must end in .md or .html, got: {filename!r}")

    # Default: under pages/ unless the caller already prefixed it.
    if rel.parts[0] != BUNDLE_LAYOUT["pages"]:
        rel = Path(BUNDLE_LAYOUT["pages"]) / rel

    target = bundle / rel
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(body, encoding="utf-8")
    return {"bundle_dir": str(bundle), "written": [str(rel)]}


# ---------------------------------------------------------------------------
# scoring & ingestion programs
# ---------------------------------------------------------------------------

def _write_program(
    bundle: Path,
    program_dir_key: str,
    script_filename: str,
    script_body: str,
    metadata_command: str,
) -> list[str]:
    program_dir = bundle / BUNDLE_LAYOUT[program_dir_key]
    program_dir.mkdir(parents=True, exist_ok=True)

    script_path = program_dir / script_filename
    script_path.write_text(script_body, encoding="utf-8")
    os.chmod(script_path, 0o755)

    meta_path = program_dir / "metadata.yaml"
    meta_path.write_text(yaml.safe_dump({"command": metadata_command}, sort_keys=False), encoding="utf-8")

    rel_dir = BUNDLE_LAYOUT[program_dir_key]
    return [f"{rel_dir}/{script_filename}", f"{rel_dir}/metadata.yaml"]


def write_scoring_program(
    slug: str,
    script: str,
    *,
    script_filename: str = "score.py",
    command: str | None = None,
    root_dir: str | None = None,
) -> dict[str, Any]:
    """Write scoring_program/{script_filename, metadata.yaml}.

    The default command matches the path layout Codabench gives the scoring
    program at runtime (see Competition-Bundle-Structure.md):
        /app/program/<script>  /app/input  /app/output
    """
    bundle = resolve_bundle_dir(slug, root_dir)
    if not bundle.exists():
        raise FileNotFoundError(f"bundle not initialised: {bundle}")

    if command is None:
        command = f"python3 /app/program/{script_filename} /app/input /app/output"

    written = _write_program(bundle, "scoring_program", script_filename, script, command)
    return {"bundle_dir": str(bundle), "written": written, "command": command}


def write_ingestion_program(
    slug: str,
    script: str,
    *,
    script_filename: str = "ingestion.py",
    command: str | None = None,
    root_dir: str | None = None,
) -> dict[str, Any]:
    """Write ingestion_program/{script_filename, metadata.yaml}.

    Default command mirrors the docs' Submission-Docker-Container-Layout:
        python3 /app/program/<script> /app/input_data /app/output /app/program /app/ingested_program
    """
    bundle = resolve_bundle_dir(slug, root_dir)
    if not bundle.exists():
        raise FileNotFoundError(f"bundle not initialised: {bundle}")

    if command is None:
        command = (
            f"python3 /app/program/{script_filename} "
            "/app/input_data /app/output /app/program /app/ingested_program"
        )

    written = _write_program(bundle, "ingestion_program", script_filename, script, command)
    return {"bundle_dir": str(bundle), "written": written, "command": command}


# ---------------------------------------------------------------------------
# solutions, data
# ---------------------------------------------------------------------------

def write_solution(slug: str, files: dict[str, str], *, subdir: str = "solution_baseline", root_dir: str | None = None) -> dict[str, Any]:
    """Write a baseline solution as a folder of text files under solutions/<subdir>/.

    `files` is a mapping {relative_path_within_solution: file_body}. We do not
    handle binary data here — for binaries the caller should drop files in
    place and call attach_data with from_path=, which copies bytes.
    """
    bundle = resolve_bundle_dir(slug, root_dir)
    if not bundle.exists():
        raise FileNotFoundError(f"bundle not initialised: {bundle}")
    if not files:
        raise ValueError("write_solution requires at least one file")

    sol_dir = bundle / BUNDLE_LAYOUT["solutions"] / subdir
    sol_dir.mkdir(parents=True, exist_ok=True)

    written: list[str] = []
    for rel_str, body in files.items():
        rel = Path(rel_str)
        if rel.is_absolute() or ".." in rel.parts:
            raise ValueError(f"solution file path must be relative inside the bundle: {rel_str!r}")
        path = sol_dir / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body, encoding="utf-8")
        written.append(str(Path(BUNDLE_LAYOUT["solutions"]) / subdir / rel))
    return {"bundle_dir": str(bundle), "written": written}


def attach_data(
    slug: str,
    *,
    target: str,
    files: dict[str, str] | None = None,
    from_path: str | None = None,
    root_dir: str | None = None,
) -> dict[str, Any]:
    """Place files into one of the bundle's data directories.

    Args:
        target: one of "reference_data", "input_data", "starting_kit", "public_data"
        files:  mapping {relative_path: text content} written as UTF-8 text
        from_path: if set, copy this file or directory tree into the target dir.
                   `files` and `from_path` are mutually exclusive.
    """
    if target not in BUNDLE_LAYOUT or target in {"pages", "scoring_program", "ingestion_program", "solutions"}:
        raise ValueError(
            f"attach_data target must be one of "
            f"reference_data|input_data|starting_kit|public_data, got {target!r}"
        )
    if (files is None) == (from_path is None):
        raise ValueError("provide exactly one of `files` or `from_path`")

    bundle = resolve_bundle_dir(slug, root_dir)
    if not bundle.exists():
        raise FileNotFoundError(f"bundle not initialised: {bundle}")

    target_dir = bundle / BUNDLE_LAYOUT[target]
    target_dir.mkdir(parents=True, exist_ok=True)
    written: list[str] = []

    if files is not None:
        for rel_str, body in files.items():
            rel = Path(rel_str)
            if rel.is_absolute() or ".." in rel.parts:
                raise ValueError(f"file path must be relative inside the bundle: {rel_str!r}")
            path = target_dir / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(body, encoding="utf-8")
            written.append(str(Path(BUNDLE_LAYOUT[target]) / rel))
    else:
        src = Path(from_path).expanduser().resolve()
        if not src.exists():
            raise FileNotFoundError(f"from_path does not exist: {src}")
        if src.is_dir():
            for p in src.rglob("*"):
                if p.is_file():
                    rel = p.relative_to(src)
                    dst = target_dir / rel
                    dst.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(p, dst)
                    written.append(str(Path(BUNDLE_LAYOUT[target]) / rel))
        else:
            dst = target_dir / src.name
            shutil.copy2(src, dst)
            written.append(str(Path(BUNDLE_LAYOUT[target]) / src.name))

    return {"bundle_dir": str(bundle), "target": target, "written": written}


# ---------------------------------------------------------------------------
# Validate
# ---------------------------------------------------------------------------

@dataclass
class ValidationIssue:
    severity: str  # "error" | "warning"
    where: str     # human-readable locator
    message: str

    def to_dict(self) -> dict[str, str]:
        return {"severity": self.severity, "where": self.where, "message": self.message}


def _load_yaml(path: Path) -> Any:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def validate_bundle(slug: str, root_dir: str | None = None) -> dict[str, Any]:
    """Local lint pass over a bundle. Returns issues; does not modify files.

    Checks (everything is best-effort but rules out the most common errors
    that cause uploads to be rejected):

      1. competition.yaml parses and has required top-level keys.
      2. Every file referenced from competition.yaml exists.
      3. Every leaderboard column.key appears at least once as a key written by
         the scoring program (we statically scan score.py text for
         `json.dump(...)` or `scores.json` keys; if we can't be sure, we warn).
      4. Each scoring/ingestion program has a metadata.yaml with a `command:`.
      5. Phases are sorted, do not overlap, and reference declared tasks.
      6. Tasks referenced from phases/solutions exist by index.
    """
    bundle = resolve_bundle_dir(slug, root_dir)
    issues: list[ValidationIssue] = []

    yaml_path = bundle / "competition.yaml"
    if not yaml_path.exists():
        return {
            "bundle_dir": str(bundle),
            "ok": False,
            "issues": [ValidationIssue("error", "competition.yaml", "missing").to_dict()],
        }

    try:
        comp = _load_yaml(yaml_path)
    except yaml.YAMLError as e:
        return {
            "bundle_dir": str(bundle),
            "ok": False,
            "issues": [ValidationIssue("error", "competition.yaml", f"YAML parse error: {e}").to_dict()],
        }
    if not isinstance(comp, dict):
        return {
            "bundle_dir": str(bundle),
            "ok": False,
            "issues": [ValidationIssue("error", "competition.yaml", "top level must be a mapping").to_dict()],
        }

    # 1. required keys
    for k in _COMPETITION_KEYS_REQUIRED:
        if k not in comp:
            issues.append(ValidationIssue("error", "competition.yaml", f"missing required key '{k}'"))

    # helper to resolve path references
    def _resolve(rel: str) -> Path:
        return (bundle / rel).resolve()

    # 2. file references
    for key in ("image", "terms"):
        ref = comp.get(key)
        if isinstance(ref, str) and not _resolve(ref).exists():
            issues.append(ValidationIssue("error", f"competition.yaml:{key}", f"referenced file does not exist: {ref}"))

    pages = comp.get("pages") or []
    for i, page in enumerate(pages):
        if not isinstance(page, dict):
            issues.append(ValidationIssue("error", f"pages[{i}]", "entry must be a mapping"))
            continue
        for k in ("title", "file"):
            if k not in page:
                issues.append(ValidationIssue("error", f"pages[{i}]", f"missing '{k}'"))
        ref = page.get("file")
        if isinstance(ref, str) and not _resolve(ref).exists():
            issues.append(ValidationIssue("error", f"pages[{i}].file", f"page file does not exist: {ref}"))

    # 6. task index lookup
    tasks = comp.get("tasks") or []
    task_by_index: dict[int, dict[str, Any]] = {}
    for i, t in enumerate(tasks):
        if not isinstance(t, dict):
            issues.append(ValidationIssue("error", f"tasks[{i}]", "entry must be a mapping"))
            continue
        idx = t.get("index")
        if not isinstance(idx, int):
            issues.append(ValidationIssue("error", f"tasks[{i}]", "missing integer 'index'"))
            continue
        if idx in task_by_index:
            issues.append(ValidationIssue("error", f"tasks[{i}]", f"duplicate task index {idx}"))
        task_by_index[idx] = t

        # task file references
        for key in ("input_data", "reference_data", "scoring_program", "ingestion_program"):
            ref = t.get(key)
            if isinstance(ref, str) and not _resolve(ref).exists():
                issues.append(ValidationIssue("error", f"tasks[{i}].{key}", f"referenced path does not exist: {ref}"))

        # If a program is a directory, it must carry a runnable metadata file.
        # Codabench accepts BOTH `metadata.yaml` and the legacy extensionless
        # `metadata` (production bundles use either — verified against the
        # STYLE-TRANS-FAIR reference bundle, Codabench competition #601).
        def _program_metadata(path: Path) -> Path | None:
            for candidate in ("metadata.yaml", "metadata"):
                if (path / candidate).is_file():
                    return path / candidate
            return None

        sp = t.get("scoring_program")
        if isinstance(sp, str):
            sp_path = _resolve(sp)
            if sp_path.is_dir():
                meta = _program_metadata(sp_path)
                if meta is None:
                    issues.append(ValidationIssue("error", f"tasks[{i}].scoring_program", "missing metadata.yaml (or legacy 'metadata')"))
                else:
                    try:
                        meta_data = _load_yaml(meta)
                        if not isinstance(meta_data, dict) or not meta_data.get("command"):
                            issues.append(ValidationIssue("error", f"tasks[{i}].scoring_program/{meta.name}", "missing 'command'"))
                    except yaml.YAMLError as e:
                        issues.append(ValidationIssue("error", f"tasks[{i}].scoring_program/{meta.name}", f"YAML parse error: {e}"))
        ip = t.get("ingestion_program")
        if isinstance(ip, str):
            ip_path = _resolve(ip)
            if ip_path.is_dir():
                if _program_metadata(ip_path) is None:
                    issues.append(ValidationIssue("error", f"tasks[{i}].ingestion_program", "missing metadata.yaml (or legacy 'metadata')"))

    # 5. phases
    phases = comp.get("phases") or []
    last_end = None
    for i, p in enumerate(phases):
        if not isinstance(p, dict):
            issues.append(ValidationIssue("error", f"phases[{i}]", "entry must be a mapping"))
            continue
        for k in ("name", "start"):
            if k not in p:
                issues.append(ValidationIssue("error", f"phases[{i}]", f"missing required '{k}'"))
        for t_idx in p.get("tasks") or []:
            if t_idx not in task_by_index:
                issues.append(ValidationIssue("error", f"phases[{i}].tasks", f"references unknown task index {t_idx}"))
        # date ordering: only catch the trivially broken case
        s, e = p.get("start"), p.get("end")
        if isinstance(s, str) and isinstance(e, str) and s > e:
            issues.append(ValidationIssue("error", f"phases[{i}]", f"start ({s}) is after end ({e})"))
        if last_end is not None and isinstance(s, str) and isinstance(last_end, str) and s < last_end:
            issues.append(ValidationIssue("warning", f"phases[{i}]", f"start ({s}) precedes previous phase end ({last_end})"))
        if isinstance(e, str):
            last_end = e

    # solutions
    for i, sol in enumerate(comp.get("solutions") or []):
        if not isinstance(sol, dict):
            issues.append(ValidationIssue("error", f"solutions[{i}]", "entry must be a mapping"))
            continue
        ref = sol.get("path")
        if isinstance(ref, str) and not _resolve(ref).exists():
            issues.append(ValidationIssue("error", f"solutions[{i}].path", f"path does not exist: {ref}"))
        for t_idx in sol.get("tasks") or []:
            if t_idx not in task_by_index:
                issues.append(ValidationIssue("error", f"solutions[{i}].tasks", f"references unknown task index {t_idx}"))

    # 3. leaderboards ↔ scoring program scores.json keys
    leaderboards = comp.get("leaderboards") or []
    expected_keys: set[str] = set()
    for i, lb in enumerate(leaderboards):
        if not isinstance(lb, dict):
            issues.append(ValidationIssue("error", f"leaderboards[{i}]", "entry must be a mapping"))
            continue
        for k in ("title", "key", "columns"):
            if k not in lb:
                issues.append(ValidationIssue("error", f"leaderboards[{i}]", f"missing required '{k}'"))
        for j, col in enumerate(lb.get("columns") or []):
            if not isinstance(col, dict):
                issues.append(ValidationIssue("error", f"leaderboards[{i}].columns[{j}]", "must be a mapping"))
                continue
            for k in ("title", "key", "index"):
                if k not in col:
                    issues.append(ValidationIssue("error", f"leaderboards[{i}].columns[{j}]", f"missing '{k}'"))
            # 'computation' columns are derived — they don't need to appear in scores.json
            if "computation" in col:
                continue
            if isinstance(col.get("key"), str):
                expected_keys.add(col["key"])

    # Static scan: do score.py files literally write each expected key?
    score_files: list[Path] = []
    for sp_dir in [bundle / BUNDLE_LAYOUT["scoring_program"]]:
        if sp_dir.is_dir():
            score_files.extend(p for p in sp_dir.rglob("*.py"))
    for t in tasks:
        sp = t.get("scoring_program") if isinstance(t, dict) else None
        if isinstance(sp, str):
            sp_path = _resolve(sp)
            if sp_path.is_dir():
                score_files.extend(p for p in sp_path.rglob("*.py"))
    score_text = "\n".join(p.read_text(encoding="utf-8", errors="replace") for p in score_files)
    for key in sorted(expected_keys):
        if score_text and (f"'{key}'" not in score_text and f'"{key}"' not in score_text):
            issues.append(ValidationIssue(
                "warning",
                "leaderboards ↔ scoring",
                f"leaderboard key '{key}' not found as a literal in any score.py — make sure scores.json writes it.",
            ))

    ok = not any(i.severity == "error" for i in issues)
    return {
        "bundle_dir": str(bundle),
        "ok": ok,
        "issues": [i.to_dict() for i in issues],
        "leaderboard_keys_expected": sorted(expected_keys),
    }


# ---------------------------------------------------------------------------
# Zip
# ---------------------------------------------------------------------------

def zip_bundle(slug: str, root_dir: str | None = None, output: str | None = None) -> dict[str, Any]:
    """Produce <slug>.zip with competition.yaml AT THE ROOT of the zip.

    By far the most common bundle upload error is zipping the *containing
    folder* rather than its contents. We always zip contents-only so that
    `competition.yaml` is at the zip's root.
    """
    bundle = resolve_bundle_dir(slug, root_dir)
    if not bundle.exists():
        raise FileNotFoundError(f"bundle not initialised: {bundle}")
    yaml_at_root = bundle / "competition.yaml"
    if not yaml_at_root.exists():
        raise FileNotFoundError(f"competition.yaml missing at {yaml_at_root}; nothing to zip")

    out_path = Path(output).expanduser().resolve() if output else (bundle.parent / f"{slug}.zip")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if out_path.exists():
        out_path.unlink()

    with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for p in bundle.rglob("*"):
            if p.is_file():
                zf.write(p, p.relative_to(bundle))
    return {
        "bundle_dir": str(bundle),
        "zip_path": str(out_path),
        "size_bytes": out_path.stat().st_size,
    }


# ---------------------------------------------------------------------------
# CLI self-test (run the data layer with no MCP involved)
# ---------------------------------------------------------------------------

def _self_test():
    """End-to-end smoke test of the data layer. Creates ./_selftest_bundle."""
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        slug = "demo"
        init_bundle(slug, root_dir=tmp, overwrite=True)
        # 200x200 logo placeholder
        import base64 as _b64, zlib as _zlib, struct as _struct
        def _make_png(w, h, r, g, b):
            def _chunk(tag, data):
                c = _struct.pack(">I", len(data)) + tag + data
                return c + _struct.pack(">I", _zlib.crc32(tag + data) & 0xFFFFFFFF)
            raw = (b"\x00" + bytes([r, g, b]) * w) * h
            return (b"\x89PNG\r\n\x1a\n"
                    + _chunk(b"IHDR", _struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0))
                    + _chunk(b"IDAT", _zlib.compress(raw, 9))
                    + _chunk(b"IEND", b""))
        (Path(tmp) / slug / "logo.png").write_bytes(_make_png(200, 200, 99, 120, 220))
        write_page(slug, "terms.md", "# Terms\nBy participating, you agree to play fair.", root_dir=tmp)
        write_page(slug, "overview.md", "# Overview\nClassify AI-generated text.", root_dir=tmp)
        write_scoring_program(
            slug,
            script=textwrap.dedent("""
                import json, sys, os, csv
                inp, out = sys.argv[1], sys.argv[2]
                # toy: read predictions.csv and reference truth.csv, compute accuracy
                with open(os.path.join(inp, 'res', 'predictions.csv')) as f:
                    preds = [r[0] for r in csv.reader(f)]
                with open(os.path.join(inp, 'ref', 'truth.csv')) as f:
                    truth = [r[0] for r in csv.reader(f)]
                acc = sum(p == t for p, t in zip(preds, truth)) / max(len(truth), 1)
                with open(os.path.join(out, 'scores.json'), 'w') as f:
                    json.dump({'accuracy': acc}, f)
            """).strip(),
            root_dir=tmp,
        )
        attach_data(slug, target="reference_data", files={"truth.csv": "1\n0\n1\n"}, root_dir=tmp)
        write_solution(slug, files={"predictions.csv": "1\n0\n1\n"}, root_dir=tmp)
        write_competition_yaml(slug, {
            "version": 2,
            "title": "AI-text detection (demo)",
            "image": "logo.png",
            "terms": "pages/terms.md",
            "pages": [
                {"title": "Overview", "file": "pages/overview.md"},
                {"title": "Terms", "file": "pages/terms.md"},
            ],
            "tasks": [{
                "index": 0,
                "name": "classify",
                "scoring_program": "scoring_program/",
                "reference_data": "reference_data/",
            }],
            "phases": [{
                "index": 0, "name": "Phase 1", "start": "2025-01-01 00:00:00",
                "end": "2025-12-31 00:00:00", "tasks": [0],
            }],
            "leaderboards": [{
                "title": "Results", "key": "main",
                "columns": [{"title": "Accuracy", "key": "accuracy", "index": 0, "sorting": "desc"}],
            }],
            "solutions": [{"index": 0, "path": "solutions/solution_baseline/", "tasks": [0]}],
        }, root_dir=tmp)
        report = validate_bundle(slug, root_dir=tmp)
        print(json.dumps(report, indent=2))
        z = zip_bundle(slug, root_dir=tmp)
        print(json.dumps(z, indent=2))


if __name__ == "__main__":  # pragma: no cover
    _self_test()
